
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class Estudiante extends javax.swing.JFrame {

    Connection con;
    
    PreparedStatement ps;
    
    ResultSet rs;
    
    public Estudiante() {
        initComponents();
        this.setSize(600,400);        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        txtComentario = new javax.swing.JTextField();
        Actualize = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Red Socia\"");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(520, 542));
        jPanel1.setLayout(null);

        txtComentario.setForeground(new java.awt.Color(51, 0, 0));
        jPanel1.add(txtComentario);
        txtComentario.setBounds(130, 210, 450, 140);

        Actualize.setBackground(new java.awt.Color(0, 0, 102));
        Actualize.setForeground(new java.awt.Color(255, 255, 255));
        Actualize.setText("Actualizar");
        Actualize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizeActionPerformed(evt);
            }
        });
        jPanel1.add(Actualize);
        Actualize.setBounds(10, 220, 108, 39);

        add.setBackground(new java.awt.Color(0, 0, 102));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Comentar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(10, 290, 108, 36);

        tabla.setBackground(new java.awt.Color(204, 204, 204));
        tabla.setForeground(new java.awt.Color(0, 0, 102));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Comentario"
            }
        ));
        tabla.setGridColor(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 569, 186);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String fecha;
        fecha = Usuario.clock();
        try{
            con = Register.Conectar();
            //especifica si es un preparedStatemente
            ps = (PreparedStatement) con.prepareStatement("INSERT INTO comentarios (comentario,fecha) VALUES(?,?)");
            //Se definen los campos con sus convertidores
            ps.setString(1,txtComentario.getText());
            ps.setString(2, fecha);

            //executedUpdate es el metoh que guarda
            int a = ps.executeUpdate();
            if (a!=0){
                JOptionPane.showMessageDialog(null,"Comentario Subido" );
            }
            //close() es el method que cierra la coneccion
            con.close();
            txtComentario.setText(null);

        }catch(SQLException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_addActionPerformed

    private void ActualizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizeActionPerformed
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Comentario");
        String[] comentario = new String[1];

        try{
            con = Register.Conectar();
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM comentarios");
            //el metodo de busqueda es executeQuery
            rs = ps.executeQuery();
            while(rs.next()){
                comentario[0] = rs.getString("comentario")+ "   fecha(" + rs.getString("fecha")+")";

                modelo.addRow(comentario);
            }

            tabla.setModel(modelo);

            JOptionPane.showMessageDialog(null,"Termino La Busqueda" );
            con.close();
        }catch(SQLException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_ActualizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualize;
    private javax.swing.JButton add;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtComentario;
    // End of variables declaration//GEN-END:variables
}
