
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class Profesor extends javax.swing.JFrame {

    Connection con;
    
    PreparedStatement ps;
    
    ResultSet rs;
    
    public Profesor() {
        initComponents();     
        this.setSize(600,400); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Red Social\"");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        tabla.setBackground(new java.awt.Color(204, 204, 204));
        tabla.setForeground(new java.awt.Color(0, 0, 102));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Comentario"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 534, 186);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 203, 127, 37);

        add.setBackground(new java.awt.Color(0, 0, 102));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Comentar");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(10, 253, 127, 36);

        Delete.setBackground(new java.awt.Color(0, 0, 102));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Eliminar Comentario");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(10, 300, 127, 40);

        txtComentario.setColumns(20);
        txtComentario.setForeground(new java.awt.Color(0, 0, 102));
        txtComentario.setRows(5);
        jScrollPane2.setViewportView(txtComentario);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(147, 203, 397, 137);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel modelo;        
        modelo = new DefaultTableModel();
        modelo.addColumn("Comentario");
        String[] comentario = new String[1];
        
        try{
            con = Register.Conectar();
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM comentarios");
            //el metodo de busqueda es executeQuery
            rs = ps.executeQuery();
            while(rs.next()){
                comentario[0] = rs.getString("comentario")+ "   fecha(" + rs.getString("fecha")+")";
                
                modelo.addRow(comentario);
            }
            
            tabla.setModel(modelo);
            
            JOptionPane.showMessageDialog(null,"Termino La Busqueda" );
            con.close();
        }catch(SQLException e){
                System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        String fecha;
        fecha = Usuario.clock();
        try{
            con = Register.Conectar();
            //especifica si es un preparedStatemente           
            ps = (PreparedStatement) con.prepareStatement("INSERT INTO comentarios (comentario,fecha) VALUES(?,?)");
            //Se definen los campos con sus convertidores
            ps.setString(1,txtComentario.getText());
            ps.setString(2, fecha);
            
            //executedUpdate es el metoh que guarda
            int a = ps.executeUpdate();
            if (a!=0){
                JOptionPane.showMessageDialog(null,"Comentario Subido" );
            }            
            //close() es el method que cierra la coneccion
            con.close();
            txtComentario.setText(null);
        }catch(SQLException e){
           System.err.println(e);
        }
    }//GEN-LAST:event_addMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        try{
            con = Register.Conectar();
            //especifica si es un preparedStatemente           
            ps = (PreparedStatement) con.prepareStatement("DELETE FROM comentarios WHERE comentario = ?");
            //Se definen los campos con sus convertidores
            ps.setString(1, txtComentario.getText());
            
            //executedUpdate es el metoh que guarda
            int a = ps.executeUpdate();
            if (a!=0){
                JOptionPane.showMessageDialog(null,"Dato Eliminado" );
            }
            
            //close() es el method que cierra la coneccion
            con.close();
            txtComentario.setText(null);
            
        }catch(SQLException e){
           System.err.println(e);
           txtComentario.setText(null);
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
        if (tabla.getSelectedRow() >= 0){                
            try{
                String Coment = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(),0));
                int z=0;
                String badComent ="";
                for(int i=0;i<Coment.length();i++){                    
                    if (Coment.charAt(i)=='f'&&Coment.charAt(i+1)=='e'&&Coment.charAt(i+2)=='c'&&Coment.charAt(i+3)=='h'&&Coment.charAt(i+4)=='a'&&Coment.charAt(i+5)=='('){
                        z=1;
                    }
                    if (z==0){
                        badComent =badComent + Coment.charAt(i);
                    }
                }
                
                txtComentario.setText(badComent);                

            }catch(Exception e){
                System.err.println(e);
            }

        }
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton add;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables
}
